version: '3.4'

services:
  redis:
        image: "redis:alpine" 
  mongodb:
        image: "mongo"
  web:
    image: ${DOCKER_REGISTRY-}evaluationcasewebapi
    build:
      context: .
      dockerfile: src/WebApi/EvaluationCase.WebApi/Dockerfile
    ports:
      - 5000:80
    restart: always
    depends_on:
          - mongodb
          - redis
    environment:
            ASPNETCORE_ENVIRONMENT: Development
  nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web
        ports:
            - 5001:80

